"""Build the port's C patches: compile for MIPS, link, recompile.

    python tools/build_patches.py

1. Every patches/*.c is compiled by Clang for 32-bit big-endian MIPS against
   the decompilation's headers and RT64's extended GBI header.
2. ld.lld links them at 0x80801000 (patches/patches.ld), leaving game symbols
   undefined and giving host functions their addresses (patches/syms.ld).
3. N64Recomp recompiles the ELF with recomp/patches.toml into
   RecompiledPatches/patches.c and patches.bin, resolving the undefined game
   symbols by name against the reference symbols tools/recompile.sh dumped.
4. patches.bin is written out as a C array (RecompiledPatches/patches_bin.c) for
   the executable to hand to librecomp.

Steps 1 to 3 run under Linux -- through WSL on Windows. Two reasons: the Linux
build of N64Recomp is the one that works (see tools/recompile.sh), and the LLVM
that winget installs on Windows is built without the MIPS backend ("No available
targets are compatible with triple mips"), while every Linux distribution's
Clang has it. Any Clang and lld from version 15 on will do; the newest installed
is used, and they need not be the same version.

Nothing written here is committed: RecompiledPatches/ is ignored, and build/
holds the objects and the ELF.
"""

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PATCHES = REPO / "patches"
DECOMP = REPO / "lib" / "Pilotwings64Decomp"
OUT = REPO / "build" / "patches"
RECOMPILED = REPO / "RecompiledPatches"
N64RECOMP = REPO / "lib" / "N64ModernRuntime" / "N64Recomp" / "build-linux" / "N64Recomp"

CFLAGS = [
    "-target", "mips", "-mips2", "-mabi=32", "-O2", "-G0",
    "-mno-abicalls", "-mno-odd-spreg", "-mno-check-zero-division",
    "-fomit-frame-pointer", "-ffast-math", "-fno-unsafe-math-optimizations",
    "-fno-builtin", "-ffreestanding", "-nostdinc",
    "-Wall", "-Wno-incompatible-library-redeclaration", "-Wno-unused-parameter",
    "-Wno-unknown-pragmas", "-Wno-unused-variable", "-Wno-missing-braces",
    "-Wno-unsupported-floating-point-opt", "-Wno-pointer-sign", "-Wno-int-conversion",
]

# The decompilation's own defines (its Makefile), less WIN32, which it sets only
# to steer IDO's headers.
DEFINES = [
    "-D_LANGUAGE_C", "-D_FINALROM", "-DNDEBUG", "-DTARGET_N64", "-DVERSION_US",
    "-DBUILD_VERSION=VERSION_D", "-DRECOMP_BUILD", "-D__sgi",
]

INCLUDES = [
    PATCHES,
    DECOMP, DECOMP / "src", DECOMP / "include", DECOMP / "include" / "kernel",
    DECOMP / "include" / "libultra", DECOMP / "include" / "libultra" / "PR",
    DECOMP / "include" / "libultra" / "compiler" / "ido",
    REPO / "lib" / "RT64" / "include",
]


def linux(args, **kwargs):
    """Run a Linux command from the repository root: natively, or through WSL."""
    args = [str(a) for a in args]
    if os.name == "nt":
        # -e runs the command directly, not through a login shell that would
        # re-parse the arguments and expand the $ in them.
        args = ["wsl", "-d", "Ubuntu", "-e", *args]
    result = subprocess.run(args, cwd=REPO, **kwargs)
    if result.returncode != 0:
        if kwargs.get("capture_output"):
            sys.stderr.write(result.stdout or "")
            sys.stderr.write(result.stderr or "")
        sys.exit(f"failed: {' '.join(args[:5])} ...")
    return result


def rel(path: Path) -> str:
    """A path relative to the repository root, in the form Linux tools accept."""
    return path.resolve().relative_to(REPO).as_posix()


def find_llvm():
    """The newest clang and ld.lld installed on the Linux side."""
    probe = (
        'for v in 21 20 19 18 17 16 15 ""; do '
        's=${v:+-$v}; '
        'c=$(command -v clang$s || true); '
        'l=$(command -v ld.lld$s || ls /usr/lib/llvm$s/bin/ld.lld 2>/dev/null || true); '
        '[ -n "$c" ] && [ -z "$CLANG" ] && CLANG=$c; '
        '[ -n "$l" ] && [ -z "$LLD" ] && LLD=$l; '
        'done; echo "$CLANG"; echo "$LLD"'
    )
    out = linux(["bash", "-c", probe], capture_output=True, text=True).stdout.splitlines()
    clang, lld = (out + ["", ""])[:2]
    if not clang.strip() or not lld.strip():
        sys.exit("clang and ld.lld were not both found on the Linux side.\n"
                 "Ubuntu: sudo apt install clang lld")
    return clang.strip(), lld.strip()


def write_bin_as_c(binary: Path, out: Path) -> int:
    data = binary.read_bytes()
    lines = [
        "/* GENERATED by tools/build_patches.py from patches.bin -- do not edit. */",
        "#include <stddef.h>",
        f"const size_t pw64_patches_bin_size = {len(data)};",
        f"const unsigned char pw64_patches_bin[{max(len(data), 1)}] = {{",
    ]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    if not data:
        lines.append("    0")
    lines.append("};")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return len(data)


def patched_functions() -> list:
    """Names of the game functions the patches replace, from the recompiled table."""
    text = (RECOMPILED / "recomp_overlays.inl").read_text(encoding="utf-8")
    names = []
    for block in re.findall(r"static FuncEntry section_\d+_recomp_(?:force_)?patch_funcs\[\] = \{(.*?)\};", text, re.S):
        names += re.findall(r"\.func = (\w+)", block)
    return names


def game_ignored_functions() -> set:
    text = (REPO / "recomp" / "pilotwings64.us.toml").read_text(encoding="utf-8")
    block = re.search(r"^ignored\s*=\s*\[(.*?)\]", text, re.S | re.M)
    return set(re.findall(r'"(\w+)"', block.group(1))) if block else set()


def game_function_addresses() -> dict:
    text = (REPO / "RecompiledFuncs" / "context" / "dump.toml").read_text(encoding="utf-8")
    return {m.group(1): int(m.group(2), 16)
            for m in re.finditer(r'\{ name = "(\w+)", vram = (0x[0-9A-Fa-f]+)', text)}


def check_and_map_replacements() -> None:
    """Every replaced function must be `ignored` in the game's config, and is mapped
    at its original address for calls that arrive through a pointer.

    Under clang-cl the recompiler's weak RECOMP_FUNC becomes a COMDAT on
    PE/COFF, which a second, strong definition collides with ("duplicate symbol")
    rather than overrides. So the game's own copy is not emitted at all: the
    function is listed under `ignored` in recomp/pilotwings64.us.toml, the patch is
    the only definition, and direct calls in the game reach it by name. Calls
    through a function pointer look the original address up instead, so the
    patch is registered there too (RecompiledPatches/patched_addresses.inl).
    """
    names = patched_functions()
    missing = sorted(set(names) - game_ignored_functions())
    if missing:
        sys.exit("These functions are replaced by patches but still recompiled from the game:\n"
                 + "".join(f"  {n}\n" for n in missing)
                 + "Add them to `ignored` in recomp/pilotwings64.us.toml, then rerun\n"
                   "tools/recompile.sh and this script.")

    addresses = game_function_addresses()
    lines = ["/* GENERATED by tools/build_patches.py -- do not edit. */",
             "static const struct { int32_t vram; recomp_func_t* func; } pw64_patched_addresses[] = {"]
    for name in names:
        if name not in addresses:
            sys.exit(f"{name} is not in the game's reference symbols")
        lines.append(f"    {{ (int32_t)0x{addresses[name]:08X}u, {name} }},")
    lines += ["    { 0, NULL },", "};"]
    (RECOMPILED / "patched_addresses.inl").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"  {len(names)} game function(s) replaced: {', '.join(names) if names else 'none'}")


def main() -> int:
    if not (REPO / "RecompiledFuncs" / "context" / "dump.toml").is_file():
        sys.exit("The game's reference symbols are missing. Run tools/recompile.sh first.")
    if not (N64RECOMP).is_file():
        sys.exit("N64Recomp is not built. Run tools/wsl_build_recompiler.sh first.")

    clang, lld = find_llvm()
    print(f"  using {clang} and {lld}")

    OUT.mkdir(parents=True, exist_ok=True)
    sources = sorted(PATCHES.glob("*.c"))
    objects = []
    for source in sources:
        obj = OUT / (source.stem + ".o")
        print(f"  cc  {rel(source)}")
        linux([clang, *CFLAGS, *DEFINES, *[f"-I{rel(p)}" for p in INCLUDES],
               "-c", rel(source), "-o", rel(obj)])
        objects.append(obj)

    elf = OUT / "patches.elf"
    print(f"  ld  {rel(elf)}")
    linux([lld, *[rel(o) for o in objects], "-nostdlib",
           "-T", rel(PATCHES / "patches.ld"), "-T", rel(PATCHES / "syms.ld"),
           "-Map", rel(OUT / "patches.map"),
           "--unresolved-symbols=ignore-all", "--emit-relocs", "-o", rel(elf)])

    if RECOMPILED.exists():
        shutil.rmtree(RECOMPILED)
    RECOMPILED.mkdir()
    print("  N64Recomp recomp/patches.toml")
    linux([rel(N64RECOMP), rel(REPO / "recomp" / "patches.toml")])

    check_and_map_replacements()
    size = write_bin_as_c(RECOMPILED / "patches.bin", RECOMPILED / "patches_bin.c")
    print(f"patches: {len(sources)} source file(s), {size} bytes of data")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
