"""Compose the recompiler config: recomp/pilotwings64.us.toml plus mdebug mappings.

Why mdebug at all: IDO writes `.mdebug` debug information into every object,
and it names *file-local* functions that the ELF symbol table does not. Most of
the game's own statics are exported by the decompilation's RECOMP_BUILD switch,
but libultra's are plain `static` -- `__CSPVoiceHandler`, the sequence player's
voice handler, for one. Such a function is reached only through a pointer stored
in data, so N64Recomp never finds it by following calls, never recompiles it, and
the port stops at the first audio frame with "no function registered at
0x80235A0C". With `use_mdebug = true` the recompiler reads those names and
addresses and recompiles the functions like any other.

Why the mappings: the parser works out which ELF section a source file's code
went to by finding one of the file's global functions. A file whose only
global functions are libultra routines the runtime reimplements (osSendMesg in
sendmesg.c) has none left to find, and the parse fails. So every source file is
mapped explicitly: kernel and libultra code went to `.kernel`, the game's own
to `.app` -- which is exactly the decompilation's splat configuration.

The list has 265 entries, derived from the decompilation's source tree, so it is
not kept in the committed config. This writes recomp/pilotwings64.us.full.toml
(ignored by git) -- the committed config with `use_mdebug` and the mappings
added -- and tools/recompile.sh runs the recompiler on that. It lives beside the
committed config so the relative paths inside mean the same thing.

    python tools/gen_mdebug_mappings.py
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DECOMP = REPO / "lib" / "Pilotwings64Decomp"
BASE = REPO / "recomp" / "pilotwings64.us.toml"
FULL = REPO / "recomp" / "pilotwings64.us.full.toml"

# Source directory -> the output section its .text was linked into.
SECTIONS = [
    ("src/libultra", ".kernel"),
    ("src/kernel", ".kernel"),
    ("src/app", ".app"),
]


def main() -> int:
    if not (DECOMP / "src").is_dir():
        sys.exit("lib/Pilotwings64Decomp is empty. Run: git submodule update --init --recursive")

    entries = []
    for subdir, section in SECTIONS:
        for source in sorted((DECOMP / subdir).rglob("*.c")):
            name = source.relative_to(DECOMP).as_posix()
            entries.append(f'    {{ filename = "{name}", input_section = ".text", output_section = "{section}" }},')

    block = "\n".join([
        "# Added by tools/gen_mdebug_mappings.py.",
        "use_mdebug = true",
        "mdebug_file_mappings = [",
        *entries,
        "]",
        "",
    ])

    text = BASE.read_text(encoding="utf-8")
    anchor = "[input]\n"
    if anchor not in text:
        sys.exit(f"{BASE} has no [input] table")
    text = text.replace(anchor, anchor + block, 1)
    header = ("# GENERATED by tools/gen_mdebug_mappings.py from pilotwings64.us.toml -- edit that\n"
              "# file, not this one.\n\n")
    FULL.write_text(header + text, encoding="utf-8", newline="\n")
    print(f"wrote {FULL.relative_to(REPO).as_posix()} ({len(entries)} mdebug file mappings)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
