"""Write the mdebug file mappings into recomp/pilotwings64.us.toml.

Why mdebug at all: IDO writes `.mdebug` debug information into every object,
and it names *file-local* functions that the ELF symbol table does not. Most of
the game's own statics are exported by the decompilation's RECOMP_BUILD switch,
but libultra's are plain `static` -- `__CSPVoiceHandler`, the sequence player's
voice handler, for one. Such a function is reached only through a pointer stored
in data, so N64Recomp never finds it by following calls, never recompiles it, and
the port stops at the first audio frame with "no function registered at
0x80235A0C". With `use_mdebug = true` the recompiler reads those names and
addresses and recompiles the functions like any other.

Why the mappings: the parser works out which ELF section a source file's code
went to by finding one of the file's global functions. A file whose only
global functions are libultra routines the runtime reimplements (osSendMesg in
sendmesg.c) has none left to find, and the parse fails. So every source file is
mapped explicitly: kernel and libultra code went to `.kernel`, the game's own
to `.app` -- which is exactly the decompilation's splat configuration.

The list is derived from the decompilation's source tree and rewritten between
two marker lines, so running this again after a submodule update is idempotent.

    python tools/gen_mdebug_mappings.py
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DECOMP = REPO / "lib" / "Pilotwings64Decomp"
CONFIG = REPO / "recomp" / "pilotwings64.us.toml"

BEGIN = "# BEGIN mdebug_file_mappings (generated by tools/gen_mdebug_mappings.py)"
END = "# END mdebug_file_mappings"

# Source directory -> the output section its .text was linked into.
SECTIONS = [
    ("src/libultra", ".kernel"),
    ("src/kernel", ".kernel"),
    ("src/app", ".app"),
]


def main() -> int:
    if not (DECOMP / "src").is_dir():
        sys.exit("lib/Pilotwings64Decomp is empty. Run: git submodule update --init --recursive")

    entries = []
    for subdir, section in SECTIONS:
        for source in sorted((DECOMP / subdir).rglob("*.c")):
            name = source.relative_to(DECOMP).as_posix()
            entries.append(f'    {{ filename = "{name}", input_section = ".text", output_section = "{section}" }},')

    block = "\n".join([BEGIN, "mdebug_file_mappings = [", *entries, "]", END])

    text = CONFIG.read_text(encoding="utf-8")
    if BEGIN in text:
        start = text.index(BEGIN)
        end = text.index(END) + len(END)
        text = text[:start] + block + text[end:]
    else:
        anchor = "use_mdebug = true\n"
        if anchor not in text:
            sys.exit(f"{CONFIG} has no `use_mdebug = true` line to put the mappings after")
        text = text.replace(anchor, anchor + block + "\n", 1)

    CONFIG.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {len(entries)} mdebug file mappings into {CONFIG.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
