"""Draw the port's launcher background and Windows icon.

The artwork is original to this project -- a flat-shaded, low-poly hang glider
over an island, in the style of the era -- and deliberately takes nothing from
the cartridge or from Nintendo's branding. The launcher background
(assets/icons/Logo.svg) and the executable's icon (assets/AppIcon.ico) are both
generated here, from the same flat-shaded elements:

    python tools/make_logo.py

The SVG is what recompui draws in the launcher; the ICO holds every standard
icon size, each rasterised from the polygons at that size with supersampling
rather than scaled from one bitmap.
"""

from pathlib import Path

from PIL import Image, ImageDraw

REPO = Path(__file__).resolve().parent.parent

# The canvas the coordinates are written in.
WIDTH, HEIGHT = 680, 360

# The launcher background: a dusk scene, dark so that recompui's white menu text
# reads over it, with everything bright kept out of the middle column where the
# menu sits (roughly x 240-440, y 130-300 on this canvas).
BACKGROUND = [
    # Sky, from deep blue overhead to a warm band at the horizon.
    ("#0b1630", [(0, 0), (680, 0), (680, 70), (0, 70)]),
    ("#10213f", [(0, 70), (680, 70), (680, 140), (0, 140)]),
    ("#172c50", [(0, 140), (680, 140), (680, 200), (0, 200)]),
    ("#243a5e", [(0, 200), (680, 200), (680, 236), (0, 236)]),
    ("#4a3f5c", [(0, 236), (680, 236), (680, 256), (0, 256)]),
    # Sea.
    ("#0d1c36", [(0, 256), (680, 256), (680, 360), (0, 360)]),
    ("#122647", [(0, 256), (300, 256), (140, 300), (0, 292)]),
    # An island low on the left.
    ("#6b5b43", [(10, 282), (80, 250), (190, 246), (250, 262), (170, 284), (60, 292)]),
    ("#1f5a33", [(40, 268), (95, 236), (150, 214), (170, 250), (120, 266)]),
    ("#17472a", [(150, 214), (215, 240), (230, 262), (170, 262), (170, 250)]),
    # A pale sun setting on the right.
    ("#f2c46a", [(600, 222), (618, 229), (626, 246), (574, 246), (582, 229)]),
    # The hang glider, small, high on the right.
    ("#e8402e", [(500, 74), (620, 40), (600, 68)]),
    ("#ffcf33", [(500, 74), (600, 68), (646, 88)]),
    ("#b82a1d", [(500, 74), (620, 40), (627, 47), (508, 77)]),
    ("#d9dde6", [(570, 73), (574, 73), (581, 100), (577, 100)]),
    ("#d9dde6", [(562, 100), (596, 96), (597, 99), (563, 103)]),
    ("#ffd2a6", [(582, 76), (589, 75), (590, 82), (583, 83)]),
]

# The icon: the same elements, brighter and close together, since it is seen at
# a few dozen pixels.
POLYGONS = [
    # Sky, in bands from pale at the horizon to deep overhead.
    ("#8fd3ff", [(0, 170), (680, 170), (680, 250), (0, 250)]),
    ("#6cc0fb", [(0, 95), (680, 95), (680, 170), (0, 170)]),
    ("#4aa8f2", [(0, 30), (680, 30), (680, 95), (0, 95)]),
    ("#2f8de6", [(0, 0), (680, 0), (680, 30), (0, 30)]),
    # Sea.
    ("#2a7fd4", [(0, 250), (680, 250), (680, 360), (0, 360)]),
    ("#3a93e3", [(0, 250), (260, 250), (120, 300), (0, 290)]),
    ("#1f6cbd", [(420, 250), (680, 250), (680, 330), (560, 300)]),
    # Island: beach, then two faces of green, then the peak.
    ("#f2dc9b", [(70, 262), (180, 226), (330, 222), (420, 250), (330, 272), (150, 280)]),
    ("#4fb04a", [(110, 252), (190, 214), (270, 176), (300, 222), (220, 256)]),
    ("#3c8f39", [(270, 176), (360, 214), (390, 246), (300, 256), (300, 222)]),
    ("#6ac65f", [(190, 214), (270, 176), (240, 232)]),
    ("#8a6b45", [(248, 188), (270, 176), (292, 190), (270, 198)]),
    # Hang glider: two wing panels, the keel shadow, the control bar and pilot.
    ("#e8402e", [(250, 120), (430, 70), (400, 112)]),
    ("#ffcf33", [(250, 120), (400, 112), (470, 140)]),
    ("#b82a1d", [(250, 120), (430, 70), (440, 80), (262, 124)]),
    ("#2d2d3a", [(356, 118), (362, 118), (372, 158), (366, 158)]),
    ("#2d2d3a", [(344, 158), (396, 152), (397, 156), (345, 162)]),
    ("#1f3b73", [(362, 132), (382, 128), (386, 140), (366, 146)]),
    ("#ffd2a6", [(378, 120), (388, 118), (390, 128), (380, 130)]),
]

ICON_SIZES = [16, 24, 32, 48, 64, 128, 256]


def write_svg(path: Path) -> None:
    lines = [
        f'<svg width="100%" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" xmlns="http://www.w3.org/2000/svg">',
        "<title>Pilotwings 64: Recompiled</title>",
        "<desc>A flat-shaded low-poly hang glider over an island at dusk. Original artwork, "
        "generated by tools/make_logo.py.</desc>",
    ]
    for colour, points in BACKGROUND:
        pts = " ".join(f"{x},{y}" for x, y in points)
        lines.append(f'<polygon points="{pts}" fill="{colour}"/>')
    lines.append("</svg>")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def render(size: int) -> Image.Image:
    """Square icon: the glider and island cropped from the middle of the scene."""
    supersample = 8
    canvas = size * supersample
    # The square region of the scene the icon shows, in scene coordinates.
    left, top, span = 180, 20, 320
    scale = canvas / span
    image = Image.new("RGBA", (canvas, canvas), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    for colour, points in POLYGONS:
        draw.polygon([((x - left) * scale, (y - top) * scale) for x, y in points], fill=colour)
    # Round the corners so the icon does not read as a bare square.
    mask = Image.new("L", (canvas, canvas), 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, canvas - 1, canvas - 1), radius=canvas // 6, fill=255)
    image.putalpha(mask)
    return image.resize((size, size), Image.LANCZOS)


def main() -> None:
    write_svg(REPO / "assets" / "icons" / "Logo.svg")
    largest = render(ICON_SIZES[-1])
    largest.save(REPO / "assets" / "AppIcon.ico", sizes=[(s, s) for s in ICON_SIZES])
    print("wrote assets/icons/Logo.svg and assets/AppIcon.ico")


if __name__ == "__main__":
    main()
